services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api-network

  # api:
  #   build: .
  #   container_name: api
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - api-network
  #   depends_on:
  #     - db

volumes:
  postgres_data:

networks:
  api-network:
    driver: bridge
